# pyproject.toml

[tool.poetry]
name = "cccpm"
version = "0.1.1"
description = "Confound-Corrected Connectome-based Predictive Modeling Python Package"
authors = [
    "Nils Winter <nils.r.winter@uni-muenster.de>",
    "MMLL <nils.r.winter@uni-muenster.de>"
]
packages = [{ include = "cccpm" }]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "<4.0,>=3.10"
numpy = "*"
pandas = "*"
scikit-learn = ">=1.6"
pingouin = "*"
nilearn = "*"
typer = "*"
pytest = "*"
pytest-cov = "*"
bleach = "*"
tinycss2 = "*"
plotly = "*"
arakawa = "*"
netplotbrain = "*"
networkx = "*"
scikit-image = "*"
tqdm = "*"
pygam = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"